<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['dep_id' => 1, 'dep_name' => 'SHS (UM-MAIN)', 'dep_full_name' => 'Senior High School', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 2, 'dep_name' => 'BED (UM-MAIN)', 'dep_full_name' => 'Basic Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 3, 'dep_name' => 'CBAE (UM-MAIN)', 'dep_full_name' => 'College of Business Administration Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 4, 'dep_name' => 'CASE (UM-MAIN)', 'dep_full_name' => 'College of Arts and Sciences Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 5, 'dep_name' => 'CTE (UM-MAIN)', 'dep_full_name' => 'College of Teachers Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 6, 'dep_name' => 'CEE (UM-MAIN)', 'dep_full_name' => 'College of Engineering Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 7, 'dep_name' => 'CLE (UM-MAIN)', 'dep_full_name' => 'College of Legal Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 8, 'dep_name' => 'PS (UM-MAIN)', 'dep_full_name' => 'Professional Schools', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 9, 'dep_name' => 'CHE (UM-MAIN)', 'dep_full_name' => 'College of Hospitality Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 10, 'dep_name' => 'CCE (UM-MAIN)', 'dep_full_name' => 'College of Computing Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 11, 'dep_name' => 'CCJE (UM-MAIN)', 'dep_full_name' => 'College of Criminal Justice Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 12, 'dep_name' => 'CAE (UM-MAIN)', 'dep_full_name' => 'College of Accounting Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 13, 'dep_name' => 'CAFAE (UM-MAIN)', 'dep_full_name' => 'College of Architecture and Fine Arts Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 14, 'dep_name' => 'CHSE (UM-MAIN)', 'dep_full_name' => 'College of Health Sciences Education', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 15, 'dep_name' => 'GSTC (UM-MAIN)', 'dep_full_name' => 'Guidance Services and Testing Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 16, 'dep_name' => 'CHS (UM-MAIN)', 'dep_full_name' => 'Center for Health Services', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 17, 'dep_name' => 'LIC (UM-MAIN)', 'dep_full_name' => 'Library and Information Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 18, 'dep_name' => 'Bookstore (UM-MAIN)', 'dep_full_name' => 'Bookstore', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 19, 'dep_name' => 'Accounting Department (UM-MAIN)', 'dep_full_name' => 'Accounting Department', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 20, 'dep_name' => 'SAO (UM-MAIN)', 'dep_full_name' => 'Student Accounting Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 21, 'dep_name' => 'AAO (UM-MAIN)', 'dep_full_name' => 'Academic Affairs Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 22, 'dep_name' => 'SSO (UM-MAIN)', 'dep_full_name' => 'Safety and Security Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 23, 'dep_name' => 'HRMD (UM-MAIN)', 'dep_full_name' => 'Human Resource Management Department', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 24, 'dep_name' => 'HRDC (UM-MAIN)', 'dep_full_name' => 'Human Resource Development Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 25, 'dep_name' => 'ICTC (UM-MAIN)', 'dep_full_name' => 'Information and Communications Technology Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 26, 'dep_name' => 'RAC Records (UM-MAIN)', 'dep_full_name' => 'RAC Records', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 27, 'dep_name' => 'RAC Admissions (UM-MAIN)', 'dep_full_name' => 'RAC Admissions', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 28, 'dep_name' => 'RPC (UM-MAIN)', 'dep_full_name' => 'Research and Publication Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 29, 'dep_name' => 'SDO (UM-MAIN)', 'dep_full_name' => 'Sports Development Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 30, 'dep_name' => 'OSA (UM-MAIN)', 'dep_full_name' => 'Office of Student Affairs', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 31, 'dep_name' => 'APS (UM-MAIN)', 'dep_full_name' => 'Academic Planning Services', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 32, 'dep_name' => 'IPAC (UM-MAIN)', 'dep_full_name' => 'Institute of Pedagogical Adavancement and Competitiveness', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 33, 'dep_name' => 'Cashiering Office (UM-MAIN)', 'dep_full_name' => 'Cashiering Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 34, 'dep_name' => 'PPMGS (UM-MAIN)', 'dep_full_name' => 'Property Management ', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 35, 'dep_name' => 'MIS (UM-MAIN)', 'dep_full_name' => 'Management Information System', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 36, 'dep_name' => 'CRMS (UM-MAIN)', 'dep_full_name' => 'Class Records Management System', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 37, 'dep_name' => 'Student Portal (UM-MAIN)', 'dep_full_name' => 'Student Portal', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 38, 'dep_name' => 'LMS (UM-MAIN)', 'dep_full_name' => 'Learning Management System', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 39, 'dep_name' => 'ERIAO (UM-MAIN)', 'dep_full_name' => 'External Relations and International Affairs Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 40, 'dep_name' => 'UM-Resolved Cases (UM-MAIN)', 'dep_full_name' => 'University of Mindanao', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 41, 'dep_name' => 'CEC (UM-MAIN)', 'dep_full_name' => 'Community Extension Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 42, 'dep_name' => 'IAO (UM-MAIN)', 'dep_full_name' => 'Internal Audit', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 43, 'dep_name' => 'DPO (UM-MAIN)', 'dep_full_name' => 'Data Privacy Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 44, 'dep_name' => 'QMO (UM-MAIN)', 'dep_full_name' => 'Quality Management Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 45, 'dep_name' => 'Office of the President (UM-MAIN)', 'dep_full_name' => 'Office of the President', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 46, 'dep_name' => 'Property Office (UM-MAIN)', 'dep_full_name' => 'Property Office', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 47, 'dep_name' => 'Purchasing Department (UM-MAIN)', 'dep_full_name' => 'Purchasing Department', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 48, 'dep_name' => 'Reproduction Center (UM-MAIN)', 'dep_full_name' => 'Reproduction Center', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 49, 'dep_name' => 'Treasury (UM-MAIN)', 'dep_full_name' => 'Treasury', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 50, 'dep_name' => 'UMFS (UM-MAIN)', 'dep_full_name' => 'UM Food Services', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 51, 'dep_name' => 'OPEAS MIS (UM MAIN)', 'dep_full_name' => 'OPEAS MIS (UM MAIN)', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 52, 'dep_name' => 'CRMS - SSO Vehicle Sticker System', 'dep_full_name' => 'CRMS - SSO Vehicle Sticker System', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 53, 'dep_name' => 'OSA (UM-DIGOS)', 'dep_full_name' => 'Office of Student Affairs', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 54, 'dep_name' => 'OPEAS HRDC (UM MAIN)', 'dep_full_name' => 'OPEAS HRDC (UM MAIN)', 'branch_id' => 'UM-MAIN', 'dep_active' => 1],
            ['dep_id' => 55, 'dep_name' => 'OSA (UM-BANSALAN)', 'dep_full_name' => 'OSA (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 56, 'dep_name' => 'RAC (UM-DIGOS)', 'dep_full_name' => 'RAC (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 57, 'dep_name' => 'Cashiering Office (UM-DIGOS)', 'dep_full_name' => 'Cashiering Office (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 58, 'dep_name' => 'SAO (UM-DIGOS)', 'dep_full_name' => 'SAO (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 59, 'dep_name' => 'ERAAO (UM-DIGOS)', 'dep_full_name' => 'ERAAO (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 60, 'dep_name' => 'GSTC (UM-DIGOS)', 'dep_full_name' => 'GSTC (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 61, 'dep_name' => 'CHS (UM-DIGOS)', 'dep_full_name' => 'CHS (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 62, 'dep_name' => 'PPMGS (UM-DIGOS)', 'dep_full_name' => 'PPMGS (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 63, 'dep_name' => 'SSO (UM-DIGOS)', 'dep_full_name' => 'SSO (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 64, 'dep_name' => 'DTE (UM-DIGOS)', 'dep_full_name' => 'DTE (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 65, 'dep_name' => 'DCJE (UM-DIGOS)', 'dep_full_name' => 'DCJE (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 66, 'dep_name' => 'DBA (UM-DIGOS)', 'dep_full_name' => 'DBA (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 67, 'dep_name' => 'DTP (UM-DIGOS)', 'dep_full_name' => 'DTP (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 68, 'dep_name' => 'SHS (UM-DIGOS)', 'dep_full_name' => 'SHS (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 69, 'dep_name' => 'DAS (UM-DIGOS)', 'dep_full_name' => 'DAS (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 70, 'dep_name' => 'DAE (UM-DIGOS)', 'dep_full_name' => 'DAE (UM-DIGOS)', 'branch_id' => 'UM-DIGOS', 'dep_active' => 1],
            ['dep_id' => 71, 'dep_name' => 'OSA (UM-PENAPLATA)', 'dep_full_name' => 'OSA (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 72, 'dep_name' => 'OSA (UM-TAGUM)', 'dep_full_name' => 'OSA (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 73, 'dep_name' => 'SAO (UM-TAGUM)', 'dep_full_name' => 'SAO (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 74, 'dep_name' => 'Cashiering Office (UM-TAGUM)', 'dep_full_name' => 'Cashiering Office (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 75, 'dep_name' => 'RAC (UM-TAGUM)', 'dep_full_name' => 'RAC (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 76, 'dep_name' => 'PPMGS (UM-TAGUM)', 'dep_full_name' => 'PPMGS (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 77, 'dep_name' => 'SSO (UM-TAGUM)', 'dep_full_name' => 'SSO (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 78, 'dep_name' => 'CHS (UM-TAGUM)', 'dep_full_name' => 'CHS (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 79, 'dep_name' => 'LIC (UM-TAGUM)', 'dep_full_name' => 'LIC (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 80, 'dep_name' => 'ERAAO (UM-TAGUM)', 'dep_full_name' => 'ERAAO (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 81, 'dep_name' => 'CEC (UM-TAGUM)', 'dep_full_name' => 'CEC (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 82, 'dep_name' => 'QUIPPER (UM-TAGUM)', 'dep_full_name' => 'QUIPPER (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 83, 'dep_name' => 'Bookstore (UM-TAGUM)', 'dep_full_name' => 'Bookstore (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 84, 'dep_name' => 'ICT (UM-TAGUM)', 'dep_full_name' => 'ICT (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 85, 'dep_name' => 'Director\'s Office (UM-BANSALAN)', 'dep_full_name' => 'Director\'s Office (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 86, 'dep_name' => 'Dean\'s Office (UM-BANSALAN)', 'dep_full_name' => 'Dean\'s Office (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 87, 'dep_name' => 'RAC (UM-BANSALAN)', 'dep_full_name' => 'RAC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 88, 'dep_name' => 'Cashiering Office (UM-BANSALAN)', 'dep_full_name' => 'Cashiering Office (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 89, 'dep_name' => 'SAO (UM-BANSALAN)', 'dep_full_name' => 'SAO (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 90, 'dep_name' => 'LIC (UM-BANSALAN)', 'dep_full_name' => 'LIC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 91, 'dep_name' => 'CHS (UM-BANSALAN)', 'dep_full_name' => 'CHS (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 92, 'dep_name' => 'GSTC (UM-BANSALAN)', 'dep_full_name' => 'GSTC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 93, 'dep_name' => 'RPC (UM-BANSALAN)', 'dep_full_name' => 'RPC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 94, 'dep_name' => 'CEC (UM-BANSALAN)', 'dep_full_name' => 'CEC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 95, 'dep_name' => 'ICTC (UM-BANSALAN)', 'dep_full_name' => 'ICTC (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 96, 'dep_name' => 'PPMGS (UM-BANSALAN)', 'dep_full_name' => 'PPMGS (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 97, 'dep_name' => 'Maintenance Office (UM-BANSALAN)', 'dep_full_name' => 'Maintenance Office (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 98, 'dep_name' => 'SSO (UM-BANSALAN)', 'dep_full_name' => 'SSO (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 99, 'dep_name' => 'BS Criminology Department (UM-BANSALAN)', 'dep_full_name' => 'BS Criminology Department (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 100, 'dep_name' => 'BSBA Department (UM-BANSALAN)', 'dep_full_name' => 'BSBA Department (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 101, 'dep_name' => 'BSMA Department (UM-BANSALAN)', 'dep_full_name' => 'BSMA Department (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 102, 'dep_name' => 'SHS (UM-BANSALAN)', 'dep_full_name' => 'SHS (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 103, 'dep_name' => 'QMO (UM-BANSALAN)', 'dep_full_name' => 'QMO (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 104, 'dep_name' => 'HRMD (UM-BANSALAN)', 'dep_full_name' => 'HRMD (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 105, 'dep_name' => 'ERAAO (UM-BANSALAN)', 'dep_full_name' => 'ERAAO (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 106, 'dep_name' => 'SDO (UM-BANSALAN)', 'dep_full_name' => 'SDO (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 107, 'dep_name' => 'Bookstore (UM-BANSALAN)', 'dep_full_name' => 'Bookstore (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 108, 'dep_name' => 'DASE (UM-BANSALAN)', 'dep_full_name' => 'DASE (UM-BANSALAN)', 'branch_id' => 'UM-BANSALAN', 'dep_active' => 1],
            ['dep_id' => 109, 'dep_name' => 'Dean\'s Office (UM-PENAPLATA)', 'dep_full_name' => 'Dean\'s Office (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 110, 'dep_name' => 'DTE (UM-PENAPLATA)', 'dep_full_name' => 'DTE (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 111, 'dep_name' => 'GSTC (UM-PANABO)', 'dep_full_name' => 'GSTC (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 112, 'dep_name' => 'QMO (UM-PANABO)', 'dep_full_name' => 'QMO (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 113, 'dep_name' => 'ERAAO (UM-PANABO)', 'dep_full_name' => 'ERAAO (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 114, 'dep_name' => 'RAC (UM-PANABO)', 'dep_full_name' => 'RAC (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 115, 'dep_name' => 'Cashiering Office (UM-PANABO)', 'dep_full_name' => 'Cashiering Office (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 116, 'dep_name' => 'SAO (UM-PANABO)', 'dep_full_name' => 'SAO (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 117, 'dep_name' => 'CHS (UM-PANABO)', 'dep_full_name' => 'CHS (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 118, 'dep_name' => 'SSO (UM-PANABO)', 'dep_full_name' => 'SSO (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 119, 'dep_name' => 'OSA (UM-PANABO)', 'dep_full_name' => 'OSA (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 120, 'dep_name' => 'LIC (UM-PANABO)', 'dep_full_name' => 'LIC (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 121, 'dep_name' => 'PPMGS (UM-PANABO)', 'dep_full_name' => 'PPMGS (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 122, 'dep_name' => 'Bookstore (UM-PANABO)', 'dep_full_name' => 'Bookstore (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 123, 'dep_name' => 'SSO (UM-PENAPLATA)', 'dep_full_name' => 'SSO (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 124, 'dep_name' => 'SAO (UM-PENAPLATA)', 'dep_full_name' => 'SAO (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 125, 'dep_name' => 'RAC (UM-PENAPLATA)', 'dep_full_name' => 'RAC (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 126, 'dep_name' => 'RPC (UM-PENAPLATA)', 'dep_full_name' => 'RPC (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 127, 'dep_name' => 'QMO (UM-PENAPLATA)', 'dep_full_name' => 'QMO (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 128, 'dep_name' => 'PPMGS (UM-PENAPLATA)', 'dep_full_name' => 'PPMGS (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 129, 'dep_name' => 'LIC (UM-PENAPLATA)', 'dep_full_name' => 'LIC (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 130, 'dep_name' => 'HRMD (UM-PENAPLATA)', 'dep_full_name' => 'HRMD (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 131, 'dep_name' => 'GSTC (UM-PENAPLATA)', 'dep_full_name' => 'GSTC (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 132, 'dep_name' => 'ERAAO (UM-PENAPLATA)', 'dep_full_name' => 'ERAAO (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 133, 'dep_name' => 'CHS (UM-PENAPLATA)', 'dep_full_name' => 'CHS (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 134, 'dep_name' => 'CEC (UM-PENAPLATA)', 'dep_full_name' => 'CEC (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 135, 'dep_name' => 'Cashiering Office (UM-PENAPLATA)', 'dep_full_name' => 'Cashiering Office (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 136, 'dep_name' => 'Bookstore (UM-PENAPLATA)', 'dep_full_name' => 'Bookstore (UM-PENAPLATA)', 'branch_id' => 'UM-PENAPLATA', 'dep_active' => 1],
            ['dep_id' => 137, 'dep_name' => 'Dean\'s Office (UM-PANABO)', 'dep_full_name' => 'Dean\'s Office (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 138, 'dep_name' => 'RPC (UM-PANABO)', 'dep_full_name' => 'RPC (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 139, 'dep_name' => 'ICTC (UM-PANABO)', 'dep_full_name' => 'ICTC (UM-PANABO)', 'branch_id' => 'UM-PANABO', 'dep_active' => 1],
            ['dep_id' => 140, 'dep_name' => 'DEE (UM-TAGUM)', 'dep_full_name' => 'Department of Engineering Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 141, 'dep_name' => 'DASE (UM-TAGUM)', 'dep_full_name' => 'Department of Arts and Sciences Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 142, 'dep_name' => 'DBAE (UM-TAGUM)', 'dep_full_name' => 'Department of Business Administration Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 143, 'dep_name' => 'DTE (UM-TAGUM)', 'dep_full_name' => 'Department of Teachers Education (UM-Tagum)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 144, 'dep_name' => 'DCE (UM-TAGUM)', 'dep_full_name' => 'Department of Accounting Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 145, 'dep_name' => 'DCJE (UM-TAGUM)', 'dep_full_name' => 'Department of Criminal Justice Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 146, 'dep_name' => 'DAE (UM-TAGUM)', 'dep_full_name' => 'Department of Accounting Education (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
            ['dep_id' => 147, 'dep_name' => 'GS (UM-TAGUM)', 'dep_full_name' => 'GS (UM-TAGUM)', 'branch_id' => 'UM-TAGUM', 'dep_active' => 1],
        ];

        // Using chunk to prevent memory issues with very large datasets
        foreach (array_chunk($data, 1000) as $chunk) {
            DB::table('departments')->insert($chunk);
        }
    }
}
