<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        @if(($validated['report_type'] ?? '') === 'intervention_summary')
            AI Confidence & Intervention Summary Report
        @elseif(($validated['report_type'] ?? '') === 'triage_audit')
            Department Rejection & Triage Audit Report
        @else
            AI Performance Report
        @endif
    </title>
    <!-- Bootstrap 5 CSS for clean printable layout -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
        }

        .report-card {
            background: #ffffff;
            border-radius: 8px;
            padding: 2.5rem;
            margin: 2rem auto;
            max-width: 900px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        }

        .report-header {
            border-bottom: 2px solid #343a40;
            padding-bottom: 1.5rem;
            margin-bottom: 2rem;
        }

        .metric-card {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 6px;
            padding: 1.25rem;
            text-align: center;
        }

        /* Styling specifically for Browser Print / Save as PDF */
        @media print {
            body {
                background-color: #ffffff !important;
            }

            .report-card {
                box-shadow: none !important;
                padding: 0 !important;
                margin: 0 !important;
                max-width: 100% !important;
            }

            .no-print {
                display: none !important;
            }

            .page-break {
                page-break-after: always;
            }
        }
    </style>
</head>
<body>

    <!-- On-Screen Control Bar (Hidden when printed/exported) -->
    <div class="no-print bg-dark text-white py-3 mb-4 shadow-sm">
        <div class="container d-flex justify-content-between align-items-center">
            <div>
                <i class="fas fa-file-pdf text-danger me-2"></i>
                <span class="fw-bold">Report Preview</span>
                <span class="text-white-50 small ms-2">({{ $reportData['date_from'] }} - {{ $reportData['date_to'] }})</span>
            </div>
            <div class="d-flex gap-2">
                <button onclick="window.print()" class="btn btn-sm btn-success px-3">
                    <i class="fas fa-print me-1"></i> Print / Save as PDF
                </button>
                <button onclick="window.close()" class="btn btn-sm btn-outline-light px-3">
                    Close Window
                </button>
            </div>
        </div>
    </div>

    <!-- Main Printable Document Container -->
    <div class="container">
        <div class="report-card">
            
            <!-- Report Header -->
            <div class="report-header d-flex justify-content-between align-items-start">
                <div>
                    <h3 class="fw-bold text-uppercase mb-1" style="letter-spacing: 0.5px;">
                        @if(($validated['report_type'] ?? '') === 'intervention_summary')
                            AI Confidence & Intervention Summary
                        @elseif(($validated['report_type'] ?? '') === 'triage_audit')
                            Department Rejection & Triage Audit
                        @else
                            System Performance Analysis
                        @endif
                    </h3>
                    <p class="text-muted small mb-0">Automated Feedback Classification & Triage System Audit</p>
                </div>
                <div class="text-end">
                    <span class="badge bg-dark px-3 py-2 text-uppercase mb-2">Official Report</span>
                    <div class="text-muted small"><strong>Generated:</strong> {{ now()->format('M d, Y h:i A') }}</div>
                    <div class="text-muted small"><strong>Generated By:</strong> {{ auth()->user()->usr_name ?? 'System Admin' }}</div>
                </div>
            </div>

            <!-- Metadata Box -->
            <div class="row mb-4">
                <div class="col-6">
                    <div class="p-3 bg-light rounded border">
                        <small class="text-uppercase text-muted fw-bold d-block mb-1">Coverage Window</small>
                        <span class="fw-bold text-dark">{{ $reportData['date_from'] }} &mdash; {{ $reportData['date_to'] }}</span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="p-3 bg-light rounded border">
                        <small class="text-uppercase text-muted fw-bold d-block mb-1">Filter Constraint Applied</small>
                        <span class="fw-bold text-dark text-capitalize">{{ str_replace('_', ' ', $validated['intervention_filter'] ?? 'all') }}</span>
                    </div>
                </div>
            </div>

            <!-- SECTION TYPE 1: AI CONFIDENCE & INTERVENTION SUMMARY -->
            @if(($validated['report_type'] ?? '') === 'intervention_summary')
                
                <h5 class="fw-bold text-secondary text-uppercase border-bottom pb-2 mb-3" style="font-size: 0.9rem;">
                    1. Executive Metric Overview
                </h5>

                <div class="row mb-4">
                    <div class="col-4">
                        <div class="metric-card">
                            <small class="text-muted text-uppercase fw-bold d-block mb-1">Total Evaluated</small>
                            <span class="fs-2 fw-bold text-dark">{{ number_format($reportData['total_predictions'] ?? 0) }}</span>
                            <small class="d-block text-muted mt-1">Feedback Submissions</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="metric-card">
                            <small class="text-muted text-uppercase fw-bold d-block mb-1">Auto-Routed</small>
                            <span class="fs-2 fw-bold text-success">{{ number_format($reportData['auto_routed'] ?? 0) }}</span>
                            <small class="d-block text-success mt-1">
                                {{ ($reportData['total_predictions'] ?? 0) > 0 ? round(($reportData['auto_routed'] / $reportData['total_predictions']) * 100, 1) : 0 }}% Automation Rate
                            </small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="metric-card">
                            <small class="text-muted text-uppercase fw-bold d-block mb-1">Human Interventions</small>
                            <span class="fs-2 fw-bold text-warning">{{ number_format($reportData['human_triaged'] ?? 0) }}</span>
                            <small class="d-block text-muted mt-1">
                                {{ ($reportData['total_predictions'] ?? 0) > 0 ? round(($reportData['human_triaged'] / $reportData['total_predictions']) * 100, 1) : 0 }}% Flagged for Triage
                            </small>
                        </div>
                    </div>
                </div>

                <h5 class="fw-bold text-secondary text-uppercase border-bottom pb-2 mb-3 mt-5" style="font-size: 0.9rem;">
                    2. Decision Logic Matrix
                </h5>

                <table class="table table-bordered align-middle text-center small mb-4">
                    <thead class="table-light text-uppercase">
                        <tr>
                            <th>Condition / Policy Range</th>
                            <th>Target State</th>
                            <th>Captured System Action</th>
                            <th>Intervention Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="fw-bold">Confidence Score &ge; Configured Threshold</td>
                            <td>Standard Category</td>
                            <td>Auto-Routed to Department</td>
                            <td><span class="badge bg-success text-white">Bypassed (No Intervention)</span></td>
                        </tr>
                        <tr>
                            <td class="fw-bold text-danger">Confidence Score &lt; Threshold</td>
                            <td>Low Precision Prediction</td>
                            <td>Routed to Admin Triage Queue</td>
                            <td><span class="badge bg-warning text-dark">Human Review Triggered</span></td>
                        </tr>
                        <tr>
                            <td class="fw-bold text-secondary">Restricted Category Override</td>
                            <td>e.g., Complaints / High Impact</td>
                            <td>Routed to Admin Triage Queue</td>
                            <td><span class="badge bg-danger text-white">Policy Override Applied</span></td>
                        </tr>
                    </tbody>
                </table>

                <h5 class="fw-bold text-secondary text-uppercase border-bottom pb-2 mb-3 mt-5" style="font-size: 0.9rem;">
                    3. Source Language Demographics
                </h5>

                <div class="row mb-4">
                    @forelse($reportData['languages'] ?? [] as $lang)
                        <div class="col-4 mb-3">
                            <div class="metric-card d-flex justify-content-between align-items-center p-3">
                                <div class="text-start">
                                    <small class="text-muted text-uppercase fw-bold d-block">{{ $lang->formatted_language }}</small>
                                    <span class="fs-4 fw-bold text-dark">{{ number_format($lang->count) }}</span>
                                </div>
                                <div>
                                    <span class="badge bg-secondary px-2 py-1" style="font-size: 0.85rem;">
                                        {{ $lang->percentage }}%
                                    </span>
                                </div>
                            </div>
                        </div>
                    @empty
                        <div class="col-12">
                            <div class="metric-card text-muted py-4">
                                No language data recorded for this period.
                            </div>
                        </div>
                    @endforelse
                </div>

            <!-- SECTION TYPE 2: DEPARTMENT REJECTION & TRIAGE AUDIT -->
            @elseif(($validated['report_type'] ?? '') === 'triage_audit')

                <h5 class="fw-bold text-secondary text-uppercase border-bottom pb-2 mb-3" style="font-size: 0.9rem;">
                    Rejection & Manual Re-assignment Audit Log
                </h5>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped align-middle small">
                        <thead class="table-dark text-uppercase">
                            <tr>
                                <th>Ticket #</th>
                                <th>Original Feedback</th>
                                <th>Rejected Department</th>
                                <th>Action By</th>
                                <th>Action Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($reportData['rejections'] ?? [] as $rejectedTicket)
                                <tr>
                                    <td class="fw-bold text-primary">#{{ $rejectedTicket->tck_id }}</td>
                                    <td>
                                        <span class="d-inline-block text-truncate" style="max-width: 250px;">
                                            "{{ $rejectedTicket->feedback->fbk_details ?? 'No details provided' }}"
                                        </span>
                                    </td>
                                    <td>
                                        <span class="badge bg-secondary">{{ $rejectedTicket->department->dep_name ?? 'N/A' }}</span>
                                    </td>
                                    <td class="fw-bold">{{ $rejectedTicket->actionBy->usr_name ?? 'Department Staff' }}</td>
                                    <td>{{ $rejectedTicket->tck_date_action ? \Carbon\Carbon::parse($rejectedTicket->tck_date_action)->format('M d, Y h:i A') : 'N/A' }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center py-4 text-muted">
                                        <i class="fas fa-check-circle text-success me-1"></i> No department rejections were recorded within this date window.
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

            @endif

            <!-- Report Footer / Sign-off -->
            <div class="mt-5 pt-4 border-top">
                <div class="row text-muted small">
                    <div class="col-8">
                        <p class="mb-0"><strong>Audit Note:</strong> This document was auto-generated by the System Dashboard. The figures reflect historical confidence scores and action logs captured in the database.</p>
                    </div>
                    <div class="col-4 text-end">
                        <p class="mb-0">Page 1 of 1</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- Automatically open the print window when loaded -->
    <script>
        window.onload = function() {
            // Short delay ensures CSS and icons render before triggering print
            setTimeout(function() {
                window.print();
            }, 500);
        };
    </script>
</body>
</html>