<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class FeedbackPrediction extends Model
{
    // Updated fillable to match your clean schema
    protected $fillable = [
        'fbk_id', 
        'model_version', 
        'verified_dept_id'
    ];

    /**
     * The Top 3 guesses generated by the AI.
     */
    public function candidates(): HasMany
    {
        return $this->hasMany(PredictionCandidate::class, 'prediction_id')->orderBy('rank', 'asc');
    }

    /**
     * The winner (Rank 1) helper.
     * This allows you to get the top guess without looping.
     */
    public function topCandidate()
    {
        return $this->hasOne(PredictionCandidate::class, 'prediction_id')->where('rank', 1);
    }

    /**
     * Get the department that was manually verified by staff.
     */
    public function verifiedDepartment(): BelongsTo
    {
        return $this->belongsTo(Department::class, 'verified_dept_id', 'dep_id');
    }

    /**
     * Helper to check if the AI was correct.
     * Returns true if the verified_dept_id matches the Rank 1 candidate.
     */
    public function wasAiCorrect(): bool
    {
        if (!$this->verified_dept_id) return false;
        
        return $this->verified_dept_id == $this->topCandidate->dep_id;
    }
}